import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import { IconLabelTabs } from "@/shared/ui";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} flex justify-center`}>
        <main className="flex h-screen flex-col items-center justify-between w-[640px]">
          {children}
          <IconLabelTabs />
        </main>
      </body>
    </html>
  );
}
